LICENSE.md

BaseALT company standard policy is GPLv2+ licensing.

License file added

---

adldap/CMakeLists.txt
adldap/active_directory.c
adldap/cmake/Modules/AddCMockaTest.cmake
adldap/cmake/Modules/AddMockedTest.cmake
adldap/test/CMakeLists.txt
adldap/test/test_adldap.c
adtool.spec

Ideally `dn2domain` function needs to return the resulting value to the pointer passed to it and use return value to emit error codes.

Update dn2domain function

---

adldap/active_directory.c

adldap: Eliminate deprecated functions

---

src/ad_interface.cpp
src/ad_interface.h
src/containers_widget.cpp
src/entry_context_menu.cpp
src/entry_context_menu.h
src/status.cpp
src/status.h

Add group_remove_user() and remove_attribute_internal() to AdInterface.
Connect group_remove_user() to Status.

"remove from group" context menu action

---

.gear/admc.spec
LICENSE.md

Samba is licensed under GPLv3 but our license is GPLv2 which is incompatible.

Change project license due to linking with Samba parts

---

src/admc/details_dialog.cpp
src/admc/details_dialog.h
src/admc/main_window.cpp
src/admc/menubar.cpp
src/common/settings.cpp
src/common/settings.h

remove setting
remove splitter between console/docked details
make instances hashmap of details dialogs a static variable in f-n
remove floating flag from details ctor

removed docked details dialog

---

.github/workflows/main.yml
Dockerfile
script/build.sh

This is minimal build job for github actions build-system.

add github action for admc

---

src/admc/rename_dialog.h
tests/test_admc.cpp
tests/test_admc.h

This pull-request resolves issues: #127 #129 #130 and #131.

Add test for renaming dialogs

---

tests/test_admc.cpp
tests/test_admc.h

Add tests for find dialog

---

CMakeLists.txt

This PR allows user extract version specified in spec file.

Add version extration from spec file for cmake

---

src/admc/ad_config.cpp
src/admc/ad_interface.cpp
src/admc/ad_object.cpp
src/admc/console.cpp
src/admc/console_drag_model.cpp
src/admc/create_dialog.cpp
src/admc/editors/octet_editor.cpp
src/admc/editors/octet_editor.h
src/admc/edits/account_option_edit.cpp
src/admc/edits/attribute_edit.h
src/admc/filter_dialog.cpp
src/admc/filter_widget/filter_builder.cpp
src/admc/filter_widget/select_classes_widget.cpp
src/admc/find_results.cpp
src/admc/object_menu.cpp
src/admc/object_model.cpp
src/admc/policies_widget.cpp
src/admc/select_container_dialog.cpp
src/admc/tabs/attributes_tab.cpp
src/admc/tabs/gpo_links_tab.h
src/admc/tabs/group_policy_tab.h
src/admc/tabs/membership_tab.cpp
src/admc/tabs/membership_tab.h
src/admc/tabs/organization_tab.h
src/common/filter.cpp
src/common/utils.cpp
src/gpgui/gui/browse_widget.cpp

- Add references to objects in for range-loops.
- Add missing override specifiers.
- Remove unused variables in lambdas.

Refactor ADMC codebase

---

src/gpgui/gui/MainWindow.cpp
src/gpgui/libgptbackend/main.cpp
src/gpgui/libgptbackend/preg/preg_parser.cpp

- Remove unused variables and functions.
- Fix variable shadowing.
- Fix uninitialized variable.

Refactor gpgui

---

tests/admc_test.h
tests/admc_test_unlock_edit.cpp
tests/admc_test_unlock_edit.h

Covers bug fixed by 82b5b3733276ac9bdc66eaa7435f79bb95b7f839

test unlock edit

---

src/admc/CMakeLists.txt
src/admc/central_widget.cpp
src/admc/central_widget.h
src/admc/console_widget/console_widget.cpp
src/admc/multi_edits/attribute_multi_edit.cpp
src/admc/multi_edits/attribute_multi_edit.h
src/admc/multi_edits/string_multi_edit.cpp
src/admc/multi_edits/string_multi_edit.h
src/admc/multi_tabs/general_multi_tab.cpp
src/admc/multi_tabs/general_multi_tab.h
src/admc/multi_tabs/properties_multi_tab.cpp
src/admc/multi_tabs/properties_multi_tab.h
src/admc/object_multi_properties_dialog.cpp
src/admc/object_multi_properties_dialog.h

Just general tab for now. Other tabs will be added separately.
Closes #95 . Not really, but only have to add other tabs.

Multi properties

---

src/adldap/ad_interface.cpp
src/adldap/ad_interface.h
src/adldap/ad_interface_p.h
src/admc/CMakeLists.txt
src/admc/central_widget.cpp
src/admc/central_widget.h
src/admc/change_dc_dialog.cpp
src/admc/change_dc_dialog.h
src/admc/console_actions.cpp
src/admc/console_actions.h
src/admc/console_types/console_object.cpp
src/admc/console_types/console_object.h
src/admc/main_window.cpp
src/admc/settings.cpp
src/admc/settings.h

Change dc dialog

---

src/admc/console_types/console_object.cpp
src/admc/console_types/console_object.h
src/admc/console_types/console_query.cpp
src/admc/console_widget/console_widget.cpp
src/admc/console_widget/console_widget.h
src/admc/console_widget/console_widget_p.h
src/admc/search_thread.cpp
src/admc/search_thread.h

Threaded fetch

---

.gear/admc.spec
src/adldap/ad_defines.h
src/admc/CMakeLists.txt
src/admc/edits/logon_hours_edit.cpp
src/admc/edits/logon_hours_edit.h
src/admc/logon_hours_dialog.cpp
src/admc/logon_hours_dialog.h
src/admc/main_window.cpp
src/admc/tabs/account_tab.cpp
tests/CMakeLists.txt
tests/admc_test_logon_hours_dialog.cpp
tests/admc_test_logon_hours_dialog.h

Logon hours dialog

---

src/adldap/ad_defines.h
src/adldap/ad_interface.cpp
src/adldap/ad_interface.h
src/adldap/ad_interface_p.h
src/admc/CMakeLists.txt
src/admc/change_dc_dialog.cpp
src/admc/change_dc_dialog.h
src/admc/connection_options_dialog.cpp
src/admc/connection_options_dialog.h
src/admc/main_window.cpp
src/admc/main_window.h
src/admc/settings.cpp
src/admc/settings.h

Add dialog for connection options. Also add a custom dc option in change dc dialog.
Closes #248

Connection options

---

script/build.sh

Update docker workflow to use cmake instead of gear.

Update dockerized workflow

---

src/admc/console_types/console_query.cpp
src/admc/console_types/console_query.h
src/admc/edit_query_item_widget.cpp
tests/CMakeLists.txt
tests/admc_test_edit_query_item_widget.cpp
tests/admc_test_edit_query_item_widget.h

Includes test for edit query widget that catches this bug.
Closes #255

Fix edit query widget

---

src/adldap/ad_interface.cpp
src/admc/policy_results_widget.cpp
tests/CMakeLists.txt
tests/admc_test.h
tests/admc_test_ad_interface.cpp
tests/admc_test_ad_interface.h
tests/admc_test_object_menu.cpp
tests/admc_test_policy_results_widget.cpp
tests/admc_test_policy_results_widget.h

And gpo f-ns.
Closes #263 and #264.

Fix policy results widget

---

.gear/admc.spec
.gear/rules
CMakeLists.txt
script/build.sh

Update .gear/admc.spec with git-based versioning release process support.

Alt release process

---

src/adldap/ad_interface.cpp
src/adldap/ad_interface.h
src/adldap/ad_interface_p.h
src/admc/central_widget.cpp

delete gpt correctly

---

src/admc/central_widget.cpp
src/admc/central_widget.h
src/admc/console_types/console_object.cpp
src/admc/console_types/console_object.h
src/admc/console_types/console_policy.cpp
src/admc/console_types/console_policy.h
src/admc/console_types/console_query.cpp
src/admc/console_types/console_query.h
src/admc/create_policy_dialog.cpp
src/admc/create_query_folder_dialog.cpp
src/admc/edit_query_folder_dialog.cpp
src/admc/rename_policy_dialog.cpp
src/admc/utils.cpp
src/admc/utils.h

Move console action slots outside of central_widget.cpp, so that they are separated by console types.

Console action slots

---

src/adldap/ad_defines.h
src/admc/CMakeLists.txt
src/admc/fsmo_dialog.cpp
src/admc/fsmo_dialog.h
src/admc/fsmo_dialog.ui
src/admc/fsmo_tab.cpp
src/admc/fsmo_tab.h
src/admc/fsmo_tab.ui
src/admc/main_window.cpp
src/admc/main_window.ui
src/admc/settings.h

Adds dialog for viewing and editing FSMO role masters. In Windows this is in "Operations Masters" dialogs scattered throughout RSAT and in some command line utilities.
Closes #313

FSMO roles

---

src/admc/console_filter_dialog.cpp
src/admc/console_filter_dialog.h
src/admc/console_filter_dialog.ui
src/admc/console_impls/object_impl.cpp
src/admc/find_widget.cpp
src/admc/search_thread.cpp
src/admc/search_thread.h
src/admc/settings.cpp
src/admc/settings.h

Object display limit

---

src/admc/console_impls/policy_impl.cpp

This implementation contains code that constructs smb path on a selected domain controller. After the path construction code performs launch of gpui-main executable with parameters specifying this path.

Implement correct launch of gpui

---

src/admc/create_computer_dialog.ui
src/admc/create_group_dialog.ui
src/admc/create_user_dialog.ui
src/admc/edit_query_item_widget.ui
src/admc/password_dialog.ui
src/admc/rename_user_dialog.ui

for those cases where default order is not adequate or
\ even completely skips some sub-widgets
closes #354

define custom tab order for some widgets

---

.gear/admc.spec
src/admc/CMakeLists.txt
src/admc/console_impls/find_policy_impl.cpp
src/admc/console_impls/find_policy_impl.h
src/admc/console_impls/found_policy_impl.cpp
src/admc/console_impls/found_policy_impl.h
src/admc/console_impls/item_type.h
src/admc/console_impls/policy_impl.cpp
src/admc/console_impls/policy_impl.h
src/admc/console_impls/policy_ou_impl.cpp
src/admc/console_impls/policy_ou_impl.h
src/admc/console_widget/console_widget.h
src/admc/find_policy_dialog.cpp
src/admc/find_policy_dialog.h
src/admc/find_policy_dialog.ui
src/admc/find_policy_dialog_p.h
src/admc/policy_results_widget.cpp
src/admc/policy_results_widget.h
src/admc/settings.h
tests/CMakeLists.txt
tests/admc_test_find_policy_dialog.cpp
tests/admc_test_find_policy_dialog.h

Find policy dialog

---

src/admc/console_widget/console_widget.cpp
src/admc/console_widget/console_widget_p.h

Fixes on incorrect word wrapping

---

src/admc/create_object_helper.cpp
src/admc/rename_object_helper.cpp
src/admc/rename_policy_dialog.cpp

fix: validation in RenameObjectHelper and CreateObjectHelper
