adtool.spec
I've tried to install `adtool` package on my `p9`-based system and it failed to find `qt5-base` dependency. It is needed to use `qt5-base-common` instead.
=> qt5-base package is non-existent; use qt5-base-common

src/ad_interface.cpp, src/ad_interface.h, src/ad_model.cpp, src/ad_model.h, src/details_widget.cpp, src/details_widget.h, src/entry_model.cpp, src/members_model.cpp, src/members_model.h, src/status_bar.cpp, src/status_bar.h
Change move_user() to move() which calls AdConnection's move() or move_user() depending on entry type.
Move drag drop logic into ad_interface.
Add is_container_like() to distinguish from is_container()..
When a group is moved, update it's member entries.
Also update member entries on other group modifications.
Update DN of entry in MembersModel when entry is moved.
(moving OU's is too complicated, will finish in future PR)
=> Drag drop groups

CMakeLists.txt, src/confirmation_dialog.cpp, src/confirmation_dialog.h, src/containers_widget.cpp, src/containers_widget.h, src/contents_widget.cpp, src/contents_widget.h, src/entry_context_menu.cpp, src/entry_context_menu.h, src/entry_widget.cpp, src/entry_widget.h, src/main_window.cpp, src/members_widget.cpp, src/members_widget.h
Move entry context menu stuff into it's own file/class. This removes the weird connections between MainWindow and EntryWidget. Also move confirmation_dialog() into it's own file since it's now used by both MainWindow and EntryContextMenu.
Also move connecting view and context menu out of EntryWidget. This way can connect context menu to any view that has DN's.
=> Entry context menu

adldap/ad_connection.cpp, adldap/include/ad_connection.h, src/ad_interface.cpp, src/ad_interface.h, src/containers_widget.cpp, src/containers_widget.h, src/contents_widget.cpp, src/contents_widget.h, src/details_widget.cpp, src/details_widget.h, src/status.cpp
Current cache is too complex and causes problems.
Changed cache to only be valid between modifications. When attributes or entries are modified, cache is invalidated completely.
So on each operation that modifies AD, all the widgets are reloaded completely.
For now Containers doesn't keep expansion state.
=> Better caching

adldap/active_directory.c
Replace handwritten sprintf's everywhere with macros that report function name, line and error automatically. Some errors are not related to LDAP functions, so added plain string message option as well for those.
=> improve AD errors

src/advanced_view_proxy.cpp, src/confirmation_dialog.cpp, src/details_widget.cpp, src/dn_column_proxy.cpp, src/main_window.cpp, src/move_dialog.cpp, src/settings.cpp, src/settings.h, src/status.cpp
Add enums for settings checkables, similarly to how settings strings are done in #57.
This guarantees that all checkables are initialized and that their text is defined.
=> Better settings

adldap/active_directory.c, adldap/ad_connection.cpp, adldap/include/active_directory.h, adldap/include/ad_connection.h, src/ad_interface.cpp, src/ad_interface.h, src/password_dialog.cpp, translations/en.ts, translations/ru.ts
Error messages can now be reworded and translated. Also error messages can be further customized depending on context. For example LDAP_CONSTRAINT_VIOLATION applies to passwords, names, attributes, etc. and in each case it's now possible to clarify the error.
For example:
_"Failed to set password for X. Error: "Constraint violation." => "Failed to set password for X. Error: "Password doesn't match rules."_
Added new AdResult struct to bundle error message with success bool.
Also remove old unused error codes.
Update translations.
=> Improve error messages

src/admc/ad_config.cpp, src/admc/ad_config.h, src/admc/ad_utils.cpp, src/admc/attribute_display.cpp, src/admc/editors/string_editor.cpp, src/admc/edits/string_edit.cpp
Store class and attribute schema as objects instead of splitting fields into separate hashmaps.
Combine preprocessing of data.
=> Ad config rework

src/admc/CMakeLists.txt, src/admc/edits/manager_edit.cpp, src/admc/filter_dialog.cpp, src/admc/filter_widget/filter_widget.cpp, src/admc/filter_widget/filter_widget.h, src/admc/filter_widget/filter_widget_normal_tab.cpp, src/admc/filter_widget/filter_widget_normal_tab.h, src/admc/filter_widget/filter_widget_simple_tab.cpp, src/admc/filter_widget/filter_widget_simple_tab.h, src/admc/filter_widget/select_classes_widget.cpp, src/admc/filter_widget/select_classes_widget.h, src/admc/find_dialog.cpp, src/admc/find_dialog.h, src/admc/find_results.cpp, src/admc/find_results.h, src/admc/move_dialog.cpp, src/admc/move_dialog.h, src/admc/object_menu.cpp, src/admc/select_container_dialog.cpp, src/admc/select_container_dialog.h, src/admc/select_dialog.cpp, src/admc/select_dialog.h, src/admc/tabs/membership_tab.cpp
Before was using select dialog for all types of selection. Also select dialog only allowed searching by class and name. Now, there is a special different dialog for selecting containers and the normal select dialog has been improved.
1. Make a different select dialog just for containers. It shows container objects as a tree, without filtering options. For containers, tree is better than list (like in select dialog). Also, filters aren't useful due to the fact that the amount of containers is almost always small.
2. Rework select dialog. Base select dialog now shows a list of currently selected objects and add/remove buttons under list. Add button opens find dialog. User operates find dialog to select some objects, then when find dialog is accepted, those objects are added to the list. …
=> Rework selecting objects

src/admc/console.cpp, src/admc/console.h, src/admc/find_results.cpp, src/admc/find_results.h, src/admc/tabs/attributes_tab.cpp, src/admc/tabs/attributes_tab.h, src/common/settings.cpp, src/common/settings.h
This PR resolves issue #92. It also adds functionality to rearrange columns in the result view.
=> add ability to save column widths in result view

src/admc/console.cpp, src/admc/console.h
This pull request addresses issue #104 . This allows user to navigate to child items in results-view and view item properties if item is not a container.
=> add navigation on double click in results view

src/admc/create_dialog.cpp, src/admc/details_dialog.cpp, src/admc/edits/attribute_edit.cpp, src/admc/edits/attribute_edit.h, src/admc/edits/password_edit.cpp, src/admc/edits/password_edit.h, src/admc/edits/string_edit.cpp, src/admc/edits/string_edit.h, src/admc/password_dialog.cpp, src/admc/password_dialog.h, src/admc/rename_dialog.cpp, src/admc/tabs/details_tab.cpp, src/admc/tabs/details_tab.h
Restore old attribute edit feature called "verify". Implement verification for unique UPN. Also rename pass edit's check_confirm to verify().
Closes #90
=> Edit verify

src/admc/ad_interface.cpp, src/admc/ad_object.cpp, src/admc/ad_object.h, src/admc/console.cpp, src/admc/console_drag_model.cpp
A couple improvements to drag and drop.
Allow computers to be added to groups via drag and drop.
Add AdObject::contains_class() for that.
Allow groups to be added to groups via drag and drop.
Improve method of disabling drag and dropping between rows.
=> Improve drag drop

CMakeLists.txt, src/admc/ad_utils.cpp, src/admc/ad_utils.h, src/admc/create_dialog.cpp, src/admc/status.cpp, src/admc/status.h, tests/CMakeLists.txt, tests/test_admc.cpp, tests/test_admc.h
make sample tests for adinterface and create dialogs
Create subdirectory called "tests".
Add ad_utils f-n dn_from_name_and_parent() used in tests.
Add temp flag called "print_errors" to Status. TEMPORARY, will be removed soon (tm), but requires AdInterface rework first.
=> setup tests

src/admc/console.cpp
Late bugfix for #108
Double clicking was changing results target but wasn't changing the current item of scope.
That's bad behavior because the logic is that results target equals to current item of scope. Caused weird behavior where you double clicked on object A in results, that switched results target to A, but scope was still targeted at B. Then when you wanted to switch back to B, you clicked on B in scope and it didnt switch (due to B already being current item).
Also, setCurrentIndex() takes care of expansions stuff for us.
=> fix double click not changing scope current item

src/admc/console.cpp
Fixes users being added to scope tree (while show non-containers setting is OFF). Users were added to scope if you dragged them. Happened because on_object_added() slot that responded to new objects appearing, put all objects into scope even if they shouldn't be there.
This also slightly alters "double-click in results" behavior. Now, if show non-containers setting is ON, it will navigate instead of opening properties for non-containers also. So essentially, double-click logic becomes: "navigate if object is in scope tree". Before it was "navigate if object is container". But, this double click behavior is now the same as in ADUC, which is ... good?
=> Fix users being add to scope

src/admc/console.cpp, src/admc/console.h
This happened if you loaded an object with many children and then refreshed it. It also affected changing settings like "Advanced View" because they refreshed the whole tree.
The problem was with sorting of the results model containing many objects. Model's sort() call appeared to create some kind of complex data structure that caused deletion of the model to take too long. For reference, if a model took 10s to load data from server and populate, it would take 60s to delete.
Fix was to put a QSortFilterProxyModel between results view and results model.
Before: view - model
After: view - proxy - model
This way, the proxy model is sorted and stores that complex data structure. The model is deleted in reasonable time (almost instantly).
In addition, the proxy model is also a better way to …
=> fix slow refresh of objects with many children

src/admc/ad_interface.cpp, src/admc/edits/attribute_edit.cpp, src/admc/edits/expiry_edit.cpp, src/admc/edits/unlock_edit.cpp, src/admc/find_results.h, src/admc/find_widget.h, src/admc/select_dialog.cpp, tests/admc_test.cpp
Fix memory leaks and other errors detected in static analysis by valgrind and PVS.
Did not include search() refactor into search_paged() so that the diff is easier to read.
=> Fix memory leaks

src/admc/ad_interface.cpp, src/admc/ad_interface.h, src/admc/ad_object.cpp, src/admc/ad_object.h, src/admc/console.cpp, src/admc/console_drag_model.cpp, src/admc/main.cpp, src/admc/object_model.cpp, src/admc/object_model.h
Remove server communication from drag and drop process. Previously drag and drop downloaded data about hovered objects to determine if object can be dropped.
Reason for this PR: communicating with the server while dragging makes the user experience laggy, especially with slower connections.
AdObject is now stored in item data of console models. ConsoleDragModel retrieves adobject's from item data and puts them in mimedata.
Had to make AdObject a qt metatype and implement stream operators. This is required for storing AdObject in QVariant and QMimeData.
Now that item data contains adobject, other item data are obsolete (dn and object class, both can be obtained from adobject). Will switch to using adobject where old item roles are used in a different PR/commit.
Added a bandaid for a qt …
=> Offline drag

src/admc/ad_interface.cpp, tests/admc_test.cpp, tests/admc_test.h
To enable recursive delete, have to give a "tree delete control" to the ldap delete function. The control is like a setting for the f-n.
Removed manual recursive delete of test arena from tests since it's not needed anymore.
Closes #132
=> Tree delete

src/admc/ad_config.cpp, src/admc/ad_config.h, src/admc/ad_interface.cpp, src/admc/ad_interface.h, src/admc/main_window.cpp, src/admc/main_window.h, src/admc/menubar.cpp, src/admc/menubar.h
This is preparation for changing how adinterface is used, which will require making adinterface not a singleton. Therefore, adconfig has to become a separate singleton.
=> Separate adconfig from adinterface

src/admc/tabs/membership_tab.cpp, src/admc/tabs/membership_tab.h
Closes #168
Closes #165 (didn't need separate edit widget, only a separate display widget)
This alters the "MemberOf" version of membership tab that is displayed for user objects.
Add primary group label that displays "Primary group: some group" below normal groups list. This replaces the "Primary" column (will remove in future) and is better because it's always visible.
Warn about trying to remove primary group/user. Before primary objects weren't selectable but that's confusing to user. Now they are selectable but if selection contains anything primary and remove button is pressed, the warning is opened (and remove is not performed).
Fix conflicts between changing primary group and adding/removing groups in apply(). Conflicts happened due to previously unknown fact that the server …
=> Fix primary group

src/admc/ad_interface.cpp, src/admc/ad_interface.h, src/admc/console_drag_model.cpp, src/admc/create_dialog.cpp, src/admc/main_window.cpp, src/admc/object_menu.cpp, src/admc/password_dialog.cpp, src/admc/properties_dialog.cpp, src/admc/rename_dialog.cpp, src/admc/rename_policy_dialog.cpp, src/admc/status.cpp, src/admc/status.h, tests/admc_test.cpp, tests/admc_test_object_menu.cpp
Rework how AD messages get to Status (status bar, status log and error log).
Previously AD instance directly used Status global instance to send it's messages to it using `Status::message()`. Status stored errors in an error log and errors were displayed with `start_error_log()` and `end_error_log()`.
Now AD collects all of it's messages. Then the code that uses this AD instance can display those messages by calling `Status::display_ad_messages(ad)`.
Basically the chain of communication changed from `App code -> AD -> Status` to `App code -> AD ||||| App code -> Status`. In addition, AD doesn't depend on Status.
Removed the print_errors flag used by tests to print AD errors, can now just do it without touching Status.
=> Messages in ad

src/admc/console.cpp, src/admc/console.h, src/admc/console_drag_model.cpp, src/admc/console_drag_model.h
This is preparation for shared console widget library. This change moves the implementation of drag logic outside the model class, so that users of the library can implement their own drag logic on their own types of items.
Currently this is slightly incomplete because in new console widget code model items have id's. Those id's will be stored in mimedata instead of adobject's but for now leaving old mimedata code in place.
Replaces #178 because that PR basically reimplements signals/slots. Should stick to standard Qt mechanisms if possible.
=> do drag and drop using signals/slots

src/admc/console.cpp, src/admc/console.h, src/admc/console_drag_model.cpp, src/admc/console_drag_model.h
more prep for console widget
Reworked drag more. Figured out that we don't have to stick to how qt models implement drag so don't have to store objects/indexes in mimedata but can store it in console at start of drag. Note that currently this looks like internals are leaking but it will be fine when console widget is there, since it will contain the "leakage".
Add start_drag() signal to console drag model. The user of model (console now, console widget in future) saves dropped indexes at this point.
Other signals now only pass the target index.
Mimedata only stores empty data with type. This is so that we can reject mimedata with other types (dragged from other models/apps).
=> improve drag

src/admc/CMakeLists.txt, src/admc/central_widget.cpp, src/admc/central_widget.h, src/admc/console_widget/console_widget.cpp, src/admc/policy_results_widget.cpp, src/admc/policy_results_widget.h, tests/CMakeLists.txt
Added policy results. This is the thing you see in results pane when a policy is selected. Displays OU's to which this policy is linked. Allows deleting OU links (via context menu) and changing "enforced" and "disabled" link options.
Added "add link" to policy items in console. You select OU's and they get linked to selected policy.
=> Policy results

src/adldap/ad_config.cpp, src/adldap/ad_config.h, src/admc/CMakeLists.txt, src/admc/central_widget.cpp, src/admc/console_types/console_object.cpp, src/admc/filter_classes_widget.cpp, src/admc/filter_classes_widget.h, src/admc/filter_custom_dialog.cpp, src/admc/filter_custom_dialog.h, src/admc/filter_dialog.cpp, src/admc/filter_dialog.h, src/admc/filter_widget/select_classes_widget.cpp, src/admc/filter_widget/select_classes_widget.h
Split filter dialog's content into 3 areas (2 are new). First one is showing all objects, i.e. no filter. Second one is selecting classes to filter for. Last one is a custom filter.
Display special text "[Filtering results]" in console's description bar when a filter is activated.
Class selection dialog in find dialog now uses the same widget as the one used in filter dialog. Because of this, "select all", "deselect all" and "cancel" buttons were removed. Also removed previous behavior where selecting all classes changes filter to accept ALL classes (those outside of listed classes as well). That feature conflicted with stuff like selecting groups (only groups were listed).
Closes #182
=> Improve filter dialog

src/admc/central_widget.cpp, src/admc/central_widget.h, src/admc/console_types/console_object.cpp, src/admc/console_types/console_object.h, src/admc/console_types/console_policy.cpp, src/admc/console_types/console_policy.h, src/admc/console_types/console_query.cpp, src/admc/console_types/console_query.h, src/admc/console_widget/console_widget.cpp, src/admc/console_widget/console_widget.h, src/admc/console_widget/console_widget_p.h, src/admc/console_widget/results_view.cpp, src/admc/console_widget/results_view.h, src/admc/console_widget/scope_model.cpp, src/admc/console_widget/scope_model.h, src/admc/create_query_folder_dialog.cpp, src/admc/create_query_item_dialog.cpp, src/admc/edit_query_folder_dialog.cpp, src/admc/edit_query_item_dialog.cpp, src/admc/edit_query_item_dialog.h, src/admc/find_results.cpp, src/admc/policy_results_widget.cpp, src/admc/policy_results_widget.h, src/admc/rename_policy_dialog.cpp, src/admc/select_policy_dialog.cpp, src/admc/utils.cpp, src/admc/utils.h
Use one model for both scope and results in console widget. Results uses setRootIndex() (as it did a couple times before...).
Simplifies a lot of things:
- removes the need to convert between scope and results items
- removes buddies
- simplifies adding items to console
- don't need to do 2 searches, 1 is enough
- don't have to manage results models
One negative is that the scope tree now slows down a bit easier when working with many objects(1000's). Before it was snappier because scope tree used a separate model.
=> Single console model

src/adldap/ad_config.cpp, src/adldap/ad_config.h, src/adldap/ad_config_p.h, src/adldap/ad_defines.h, src/adldap/ad_interface.cpp, src/adldap/ad_interface.h, src/admc/CMakeLists.txt, src/admc/console_impls/object_impl.cpp, src/admc/console_impls/object_impl.h, src/admc/create_contact_dialog.cpp, src/admc/create_contact_dialog.h, src/admc/create_contact_dialog.ui, src/admc/create_object_helper.cpp, src/admc/create_shared_folder_dialog.cpp, src/admc/create_shared_folder_dialog.h, src/admc/create_shared_folder_dialog.ui, src/admc/create_user_dialog.cpp, src/admc/create_user_dialog.h, src/admc/settings.h, src/admc/utils.cpp, src/admc/utils.h, tests/admc_test.h, tests/admc_test_create_object_dialog.cpp, tests/admc_test_create_object_dialog.h
closes #343 
Add creation of missing object types:
- inetOrgPerson
- contact
- shared folder
Also, make it so that "New" sub-menu of action menu contains only those object types that can be children of targeted parent object.
=> Improve object creation

src/admc/console_impls/policy_impl.cpp
I've added into ADMC ability to provide GPUI with group policy's display name. It can be useful for end-user to know which policy they are editing.
=> provide gpui with policy display name

src/admc/console_impls/object_impl.cpp, src/admc/console_impls/policy_impl.cpp, src/admc/console_impls/query_folder_impl.cpp, src/admc/console_impls/query_item_impl.cpp, src/admc/console_widget/console_widget.cpp, src/admc/console_widget/console_widget.h, src/admc/console_widget/console_widget_p.h, src/admc/utils.cpp, src/admc/utils.h
While working on toolbar buttons, discovered that this state is not needed. Originally it was added solely for implementing the "context menu targets current scope if clicked on empty space in results view". There's a way to implement that feature without adding state, by clearing selection of results view and reusing the existing condition in get_selected() that returns scope selection instead of results selection if results selection is empty.
Also renamed all vars and f-ns that have "action target" in them.
=> Remove action target variable

src/admc/rename_object_helper.cpp, src/admc/rename_object_helper.h, src/admc/rename_user_dialog.cpp
fixed the availability of the Ok button if the required fields are not filled
=> fix: ok button availability in rename user dialog

src/admc/rename_group_dialog.cpp
Ok button availability when no name is entered in rename group dialog. Fixing bug number 90909
=> fix ok button availability when no name is entered in rename group dialog

src/admc/create_policy_dialog.cpp, src/admc/create_policy_dialog.h, src/admc/rename_other_dialog.cpp, src/admc/rename_policy_dialog.cpp, src/admc/rename_policy_dialog.h
Fixed availability of the Ok button when the name is empty in the OU renaming dialog. Bug 90907
=> Fix ok button availability renaming ou

src/admc/create_policy_dialog.cpp, src/admc/create_policy_dialog.h, src/admc/rename_policy_dialog.cpp, src/admc/rename_policy_dialog.h
Fixed availability of the Ok button when a policy name is empty in the dialogs for renaming and creating a group policy object. Bug 90920
=> Fix ok button availability creating and renaming GPO

src/admc/create_object_helper.cpp, src/admc/rename_object_helper.cpp, src/admc/rename_policy_dialog.cpp
Reverts altlinux/admc#390 - Due to inability to input Russian characters in additional fields of user rename dialog this pull-request is reverted.
=> Revert "fix: validation in RenameObjectHelper and CreateObjectHelper"
